package com.example.adore.models.enums


enum class ProductType {
    Bottoms,
    Ethnicwear,
    DressesAndJumpsuits,
    Winterwear,
    Topwear,
    Bottomwear,
    Sportswear,
    Nightwear
}

enum class Category{
    Tops,
    Shirts,
    Tees,
    TShirts,
    Shrugs,
    JacketsAndCoats,
    TanksAndCamisoles,
    Tunics,
    ChuridarsAndLeggings,
    Dresses,
    DupattasAndStoles,
    FashionBottoms,
    KurtasAndKurtis,
    Leggings,
    PalazzosAndCulottes,
    SalwarAndPatialas,
    Skirts,
    StraightPants,
    TopsAndTunics,
    Capris,
    EthnicBottoms,
    JeansAndJeggings,
    Pants,
    Shorts,
    Trousers,
    Jumpsuits,
    Dungarees,
    Cardigans,
    CasualShirts,
    FormalShirts,
    Jackets,
    Polos,
    CasualTrousers,
    FormalTrousers,
    Jeans,
    TrackPants,
    Kurtas,
    Pyjamas,
    HoodiesAndSweatshirts,
    Sweaters,
    Swimwear,
    Joggers
}