package com.example.adore.models.enums

enum class ProductType(val gender: Gender, val headingValue: String) {
    Topwear(Gender.Unisex, "Topwear"),
    Bottomwear(Gender.Unisex, "Bottomwear"),
    Ethnicwear(Gender.Unisex, "Ethnicwear"),
    DressesAndJumpsuits(Gender.Women, "Dresses & Jumpsuits"),
    Sportswear(Gender.Unisex, "Sportswear"),
    Nightwear(Gender.Unisex, "Nightwear"),
    Winterwear(Gender.Unisex, "Winterwear"),
}

enum class Category(val gender: Gender, val type: List<ProductType>, val headingValue:String){
    Tops(Gender.Women, listOf(ProductType.Topwear), "Tops"),
    Jeans(Gender.Unisex, listOf(ProductType.Bottomwear), "Jeans"),
    Shirts(Gender.Unisex, listOf(ProductType.Topwear), "Shirts"),
    Tees(Gender.Unisex, listOf(ProductType.Sportswear), "Tees"),
    TShirts(Gender.Unisex, listOf(ProductType.Topwear), "T-Shirts"),
    Tunics(Gender.Women, listOf(ProductType.Topwear), "Tunics"),
    ChuridarsAndLeggings(Gender.Women, listOf(ProductType.Ethnicwear), "Churidars & Leggings"),
    Dresses(Gender.Women, listOf(ProductType.DressesAndJumpsuits, ProductType.Ethnicwear), "Dresses"),
    JacketsAndCoats(Gender.Unisex, listOf(ProductType.Topwear, ProductType.Winterwear), "Jackets & Coats"),
    Leggings(Gender.Women, listOf(ProductType.Bottomwear), "Leggings"),
    Palazzos(Gender.Women, listOf(ProductType.Bottomwear), "Palazzos"),
    Salwar(Gender.Women, listOf(ProductType.Ethnicwear), "Salwar"),
    Skirts(Gender.Women, listOf(ProductType.Bottomwear), "Skirts"),
    StraightPants(Gender.Women, listOf(ProductType.Bottomwear), "Straight Pants"),
    Capris(Gender.Women, listOf(ProductType.Bottomwear), "Capris"),
    EthnicBottoms(Gender.Women, listOf(ProductType.Bottomwear, ProductType.Ethnicwear), "Ethnic Bottoms"),
    Jeggings(Gender.Women, listOf(ProductType.Bottomwear), "Jeggings"),
    Shorts(Gender.Unisex, listOf(ProductType.Bottomwear), "Shorts"),
    Jumpsuits(Gender.Women, listOf(ProductType.DressesAndJumpsuits), "Jumpsuits"),
    Cardigans(Gender.Women, listOf(ProductType.Winterwear), "Cardigans"),
    CasualShirts(Gender.Men, listOf(ProductType.Topwear), "Casual Shirts"),
    FormalShirts(Gender.Men, listOf(ProductType.Topwear), "Formal Shirts"),
    Jackets(Gender.Men, listOf(ProductType.Topwear), "Jackets"),
    Polos(Gender.Men, listOf(ProductType.Topwear), "Polos"),
    CasualTrousers(Gender.Men, listOf(ProductType.Bottomwear), "Casual Trousers"),
    FormalTrousers(Gender.Men, listOf(ProductType.Bottomwear), "Formal Trousers"),
    TrackPants(Gender.Men, listOf(ProductType.Bottomwear), "Track Pants"),
    Kurtas(Gender.Unisex, listOf(ProductType.Ethnicwear), "Kurtas"),
    Pyjamas(Gender.Women, listOf(ProductType.Nightwear), "Pyjamas"),
    HoodiesAndSweatshirts(Gender.Unisex, listOf(ProductType.Winterwear), "Hoodies & SweatShirts"),
    Sweaters(Gender.Unisex, listOf(ProductType.Winterwear), "Sweaters"),
    Swimwear(Gender.Unisex, listOf(ProductType.Sportswear), "Swimwear"),
    Joggers(Gender.Unisex, listOf(ProductType.Sportswear), "Joggers")
}