package com.example.adore.models.enums

enum class ProductType(val gender: Gender) {
    Topwear(Gender.Unisex),
    Bottomwear(Gender.Unisex),
    Ethnicwear(Gender.Unisex),
    DressesAndJumpsuits(Gender.Women),
    Sportswear(Gender.Unisex),
    Nightwear(Gender.Unisex),
    Winterwear(Gender.Unisex),
}

enum class Category(val gender: Gender, val type: List<ProductType>){
    Tops(Gender.Women, listOf(ProductType.Topwear)),
    Shirts(Gender.Unisex, listOf(ProductType.Topwear)),
    Tees(Gender.Unisex, listOf(ProductType.Topwear, ProductType.Sportswear)),
    TShirts(Gender.Unisex, listOf(ProductType.Topwear)),
    JacketsAndCoats(Gender.Unisex, listOf(ProductType.Topwear, ProductType.Winterwear)),
    Tunics(Gender.Women, listOf(ProductType.Topwear)),
    ChuridarsAndLeggings(Gender.Women, listOf(ProductType.Ethnicwear)),
    Dresses(Gender.Women, listOf(ProductType.DressesAndJumpsuits, ProductType.Ethnicwear)),
    Leggings(Gender.Women, listOf(ProductType.Bottomwear)),
    Palazzos(Gender.Women, listOf(ProductType.Bottomwear)),
    Salwar(Gender.Women, listOf(ProductType.Ethnicwear)),
    Skirts(Gender.Women, listOf(ProductType.Bottomwear)),
    StraightPants(Gender.Women, listOf(ProductType.Bottomwear)),
    Capris(Gender.Women, listOf(ProductType.Bottomwear)),
    EthnicBottoms(Gender.Women, listOf(ProductType.Bottomwear, ProductType.Ethnicwear)),
    JeansAndJeggings(Gender.Women, listOf(ProductType.Bottomwear)),
    Shorts(Gender.Unisex, listOf(ProductType.Bottomwear)),
    Jumpsuits(Gender.Women, listOf(ProductType.DressesAndJumpsuits)),
    Cardigans(Gender.Women, listOf(ProductType.Winterwear)),
    CasualShirts(Gender.Men, listOf(ProductType.Topwear)),
    FormalShirts(Gender.Men, listOf(ProductType.Topwear)),
    Jackets(Gender.Men, listOf(ProductType.Topwear)),
    Polos(Gender.Men, listOf(ProductType.Topwear)),
    CasualTrousers(Gender.Men, listOf(ProductType.Bottomwear)),
    FormalTrousers(Gender.Men, listOf(ProductType.Bottomwear)),
    Jeans(Gender.Unisex, listOf(ProductType.Bottomwear)),
    TrackPants(Gender.Men, listOf(ProductType.Bottomwear)),
    Kurtas(Gender.Unisex, listOf(ProductType.Ethnicwear)),
    Pyjamas(Gender.Women, listOf(ProductType.Nightwear)),
    HoodiesAndSweatshirts(Gender.Unisex, listOf(ProductType.Winterwear)),
    Sweaters(Gender.Unisex, listOf(ProductType.Winterwear)),
    Swimwear(Gender.Unisex, listOf(ProductType.Sportswear)),
    Joggers(Gender.Unisex, listOf(ProductType.Sportswear))
}